cookies = [
 {
  "name": "language",
  "value": "fr",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": False,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1792785613,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "__gads",
  "value": "ID=2f25c8fb486ecf64:T=1539953120:S=ALNI_MZ0xjuz6YbBP0akeZ40wxYOCT91XQ",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": False,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1603025120,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "twitch.lohp.countryCode",
  "value": "FR",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": False,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1863711900,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "api_token",
  "value": "2f7e414741b311f6717f35bd5acbb4f6",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": True,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1575208196,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "twilight-user",
  "value": "{%22authToken%22:%22q9kr72h0y77v17fqqsjikc73w82bss%22%2C%22displayName%22:%22thimothe%22%2C%22id%22:%2237219140%22%2C%22login%22:%22thimothe%22%2C%22roles%22:{%22isStaff%22:False}%2C%22version%22:2}",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": True,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1576530253,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "auth-token",
  "value": "q9kr72h0y77v17fqqsjikc73w82bss",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": True,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1576530253,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 },
 {
  "name": "login",
  "value": "thimothe",
  "domain": ".twitch.tv",
  "hostOnly": False,
  "path": "/",
  "secure": True,
  "httpOnly": False,
  "session": False,
  "expirationDate": 1576530253,
  "storeId": "firefox-default",
  "sameSite": "no_restriction",
  "firstPartyDomain": ""
 }
]
